FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

# Copy everything needed for building commands
COPY . .
# Restore as distinct layers
RUN dotnet restore 
# Build and publish a release
RUN dotnet publish ./Commands/MoneyTracker.Commands.API/MoneyTracker.Commands.API.csproj -c Release -o outCommands

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build-env /App/outCommands .
EXPOSE 8080
ENV PORT 8080
ENTRYPOINT ["dotnet", "MoneyTracker.Commands.API.dll"]
