FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

# Copy everything needed for building Queries
COPY . .
# Restore as distinct layers
RUN dotnet restore 
# Build and publish a release
RUN dotnet publish ./Queries/MoneyTracker.Queries.API/MoneyTracker.Queries.API.csproj -c Release -o outQueries

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build-env /App/outQueries .
EXPOSE 8080
ENV PORT 8080
ENTRYPOINT ["dotnet", "MoneyTracker.Queries.API.dll"]
