services:
  postgres-master:
    image: "postgres:17-alpine"
    container_name: postgres-master
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DOCKER_DB_DATABASE}
      - POSTGRES_USER=${DOCKER_DB_USERNAME}
      - POSTGRES_PASSWORD=${DOCKER_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DOCKER_DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - master-database:/var/lib/postgresql/data

  be-base:
    build:
      context: .
      dockerfile: Dockerfile-Base
    image: be-base-image:latest
    command: ["true"]

  be-queries:
    build:
      context: .
      dockerfile: ./Queries/Dockerfile
    ports:
      - "1235:8080"
    environment:
      Database:Paelagus_RO: "User ID=${DOCKER_DB_USERNAME};Password=${DOCKER_DB_PASSWORD};Host=postgres-master;Port=5432;Database=${DOCKER_DB_DATABASE}"
      ASPNETCORE_ENVIRONMENT: "Development"
      Jwt:iss: ${jwt_iss}
      Jwt:aud: ${jwt_aud}
      Jwt:key: ${jwt_key}
    links:
      - postgres-master
    depends_on:
      postgres-master:
        condition: service_healthy
      be-base:
        condition: service_completed_successfully

  be-commands:
    build:
      context: .
      dockerfile: ./Commands/Dockerfile
    ports:
      - "1234:8080"
    environment:
      Database:Paelagus_RO: "User ID=${DOCKER_DB_USERNAME};Password=${DOCKER_DB_PASSWORD};Host=postgres-master;Port=5432;Database=${DOCKER_DB_DATABASE}"
      ASPNETCORE_ENVIRONMENT: "Development"
      Jwt:iss: ${jwt_iss}
      Jwt:aud: ${jwt_aud}
      Jwt:key: ${jwt_key}
    links:
      - postgres-master
    depends_on:
      postgres-master:
        condition: service_healthy
      be-base:
        condition: service_completed_successfully

volumes:
  master-database:
